# Generated by Django 2.1.3 on 2018-11-09 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Probability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
            ],
        ),
        migrations.RenameField(
            model_name='label',
            old_name='image',
            new_name='images',
        ),
        migrations.AddField(
            model_name='probability',
            name='label',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Label'),
        ),
    ]
