# Generated by Django 2.1.3 on 2018-11-09 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0002_auto_20181109_1417'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image_path',
            new_name='path',
        ),
    ]
