# Generated by Django 2.1.3 on 2018-11-11 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0003_auto_20181109_1437'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
                ('gui', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='predicted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
