# Generated by Django 2.1.3 on 2018-11-12 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('image', '0004_auto_20181112_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlabels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='image.Image')),
            ],
        ),
        migrations.RemoveField(
            model_name='label',
            name='images',
        ),
        migrations.RemoveField(
            model_name='label',
            name='user',
        ),
        migrations.AddField(
            model_name='userlabels',
            name='label',
            field=models.ManyToManyField(to='image.Label'),
        ),
    ]
