# Generated by Django 2.1.3 on 2018-11-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0005_auto_20181112_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='predicted',
        ),
        migrations.AddField(
            model_name='image',
            name='variance',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
