# Generated by Django 2.1.3 on 2018-11-12 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0006_auto_20181112_2040'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='image',
            managers=[
            ],
        ),
    ]
