# Generated by Django 2.1.3 on 2018-11-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0007_auto_20181112_2104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='path',
            new_name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='data',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
