# Generated by Django 2.1.3 on 2018-11-13 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0008_auto_20181112_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='count_userlabels',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
