# Generated by Django 2.1.3 on 2018-12-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0011_auto_20181207_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
