# Generated by Django 2.1.3 on 2018-12-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0013_auto_20181207_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='data',
            field=models.ImageField(default='media/default.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='name', max_length=200),
            preserve_default=False,
        ),
    ]
