# Generated by Django 2.1.3 on 2018-12-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0015_auto_20181207_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='probability',
            name='value',
            field=models.BooleanField(),
        ),
    ]
