# Generated by Django 2.1.3 on 2018-12-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0017_userlabels_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probability',
            name='image',
        ),
        migrations.RemoveField(
            model_name='probability',
            name='label',
        ),
        migrations.DeleteModel(
            name='Probability',
        ),
    ]
