# Generated by Django 2.1.3 on 2019-01-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0018_auto_20181223_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='count_userlabels',
        ),
        migrations.AddField(
            model_name='userlabels',
            name='uncertain',
            field=models.BooleanField(null=True),
        ),
    ]
