# Generated by Django 2.1.3 on 2019-01-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0019_auto_20190108_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlabels',
            name='uncertain',
            field=models.BooleanField(default=False),
        ),
    ]
