= Dokumentation

== Modell

=== Image
Metadaten eines Bildes

* name: Dateiname
* variance: Varianz der Wahrscheinlichkeiten des NN
* data: Pfad zum Bild
* count_userlabels: Anzahl der User, die dieses Bild bereits gelabeled haben

=== Label
Alle Instrumente, die gelabeled werden können

* name: Name des Instruments

=== Userlabels
Vom User gesetzte Labels eines Bildes

* image: Bild
* author: User, der das Bild gelabeled hat
* label: Instrumente, die im Bild vorhanden sind

=== Probability
Die Wahrscheinlichkeit für ein Instrument in einem Bild

* image: Bild
* label: Instrument
* value: Wahrscheinlichkeit (zwischen 0 und 1)

== Datenbankinterfaces

=== GUI

nächstes Bild holen
[source,python]
Image.objects.next_image()

Labels eines Bildes holen
[source,python]
Probability.objects.get_image_labels(image)

Labels eines Bildes setzen
[source,python]
Userlabels.objects.set_userlabels(image, user, label_set)

oder mit label_set als Liste von Strings
[source,python]
Userlabels.objects.set_userlabels_str(image, user, label_set)

bestimmte Anzahl von zuletzt gelabelten Bildern holen (default 20)
[source,python]
get_labeled_images(user, amount)


=== NN Manager

neue Labels in CSV schreiben
[source,python]
Userlabels.objects.write_csv()

über server:
[source, http]
http://localhost:8000/image/annotations

Wahrscheinlichkeiten für ein Bild speichern
[source,python]
labels = [0.1, 0.2, 0.1, 0.8, 0.1]
Probability.objects.set_probabilities(image, labels)

Python file upload (http POST)

https://gist.github.com/yoavram/4351498
